<script>
  import * as Icon from '$lib';
  const random_hex_color_code = () => {
    let n = (Math.random() * 0xfffff * 1000000).toString(16);
    return '#' + n.slice(0, 6);
  };
  import { AcademicCap } from '$lib';
</script>

<Icon.AcademicCap size="40" color={random_hex_color_code()} tabindex="-1" />
<Icon.AdjustmentsHorizontal size="40" color={random_hex_color_code()} tabindex="-1" />
<Icon.AdjustmentsVertical size="40" color={random_hex_color_code()} tabindex="-1" />
<Icon.ArchiveBox size="40" color={random_hex_color_code()} />
<Icon.ArchiveBoxArrowDown size="40" color={random_hex_color_code()} />
<Icon.ArchiveBoxXMark size="40" color={random_hex_color_code()} />
<Icon.ArrowDown size="40" color={random_hex_color_code()} />
<Icon.ArrowDownCircle size="40" color={random_hex_color_code()} />
<Icon.ArrowDownLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowDownOnSquare size="40" color={random_hex_color_code()} />
<Icon.ArrowDownOnSquareStack size="40" color={random_hex_color_code()} />
<Icon.ArrowDownRight size="40" color={random_hex_color_code()} />
<Icon.ArrowDownTray size="40" color={random_hex_color_code()} />
<Icon.ArrowLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowLeftCircle size="40" color={random_hex_color_code()} />
<Icon.ArrowLeftOnRectangle size="40" color={random_hex_color_code()} />
<Icon.ArrowLongDown size="40" color={random_hex_color_code()} />
<Icon.ArrowLongLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowLongRight size="40" color={random_hex_color_code()} />
<Icon.ArrowLongUp size="40" color={random_hex_color_code()} />
<Icon.ArrowPath size="40" color={random_hex_color_code()} />
<Icon.ArrowRight size="40" color={random_hex_color_code()} />
<Icon.ArrowRightCircle size="40" color={random_hex_color_code()} />
<Icon.ArrowRightOnRectangle size="40" color={random_hex_color_code()} />
<Icon.ArrowTopRightOnSquare size="40" color={random_hex_color_code()} />
<Icon.ArrowTrendingDown size="40" color={random_hex_color_code()} />
<Icon.ArrowTrendingUp size="40" color={random_hex_color_code()} />
<Icon.ArrowUp size="40" color={random_hex_color_code()} />
<Icon.ArrowUpCircle size="40" color={random_hex_color_code()} />
<Icon.ArrowUpLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowUpOnSquare size="40" color={random_hex_color_code()} />
<Icon.ArrowUpOnSquareStack size="40" color={random_hex_color_code()} />
<Icon.ArrowUpRight size="40" color={random_hex_color_code()} />
<Icon.ArrowUpTray size="40" color={random_hex_color_code()} />
<Icon.ArrowUturnDown size="40" color={random_hex_color_code()} />
<Icon.ArrowUturnLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowUturnRight size="40" color={random_hex_color_code()} />
<Icon.ArrowUturnUp size="40" color={random_hex_color_code()} />
<Icon.ArrowsPointingIn size="40" color={random_hex_color_code()} />
<Icon.ArrowsPointingOut size="40" color={random_hex_color_code()} />
<Icon.ArrowsRightLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowsUpDown size="40" color={random_hex_color_code()} />
<Icon.AtSymbol size="40" color={random_hex_color_code()} />
<Icon.Backspace size="40" color={random_hex_color_code()} />
<Icon.Backward size="40" color={random_hex_color_code()} />
<Icon.Banknotes size="40" color={random_hex_color_code()} />
<Icon.Bars2 size="40" color={random_hex_color_code()} />
<Icon.Bars3 size="40" color={random_hex_color_code()} />
<Icon.Bars3BottomLeft size="40" color={random_hex_color_code()} />
<Icon.Bars3BottomRight size="40" color={random_hex_color_code()} />
<Icon.Bars3CenterLeft size="40" color={random_hex_color_code()} />
<Icon.Bars4 size="40" color={random_hex_color_code()} />
<Icon.BarsArrowDown size="40" color={random_hex_color_code()} />
<Icon.BarsArrowUp size="40" color={random_hex_color_code()} />
<Icon.Beaker size="40" color={random_hex_color_code()} />
<Icon.Bell size="40" color={random_hex_color_code()} />
<Icon.BellAlert size="40" color={random_hex_color_code()} />
<Icon.BellSlash size="40" color={random_hex_color_code()} />
<Icon.BellSnooze size="40" color={random_hex_color_code()} />
<Icon.Bolt size="40" color={random_hex_color_code()} />
<Icon.BoltSlash size="40" color={random_hex_color_code()} />
<Icon.BookOpen size="40" color={random_hex_color_code()} />
<Icon.Bookmark size="40" color={random_hex_color_code()} />
<Icon.BookmarkSlash size="40" color={random_hex_color_code()} />
<Icon.BookmarkSquare size="40" color={random_hex_color_code()} />
<Icon.Briefcase size="40" color={random_hex_color_code()} />
<Icon.BuildingLibrary size="40" color={random_hex_color_code()} />
<Icon.BuildingOffice size="40" color={random_hex_color_code()} />
<Icon.BuildingOffice2 size="40" color={random_hex_color_code()} />
<Icon.BuildingStorefront size="40" color={random_hex_color_code()} />
<Icon.Cake size="40" color={random_hex_color_code()} />
<Icon.Calculator size="40" color={random_hex_color_code()} />
<Icon.Calendar size="40" color={random_hex_color_code()} />
<Icon.CalendarDays size="40" color={random_hex_color_code()} />
<Icon.Camera size="40" color={random_hex_color_code()} />
<Icon.ChartBar size="40" color={random_hex_color_code()} />
<Icon.ChartBarSquare size="40" color={random_hex_color_code()} />
<Icon.ChartPie size="40" color={random_hex_color_code()} />
<Icon.ChatBubbleBottomCenter size="40" color={random_hex_color_code()} />
<Icon.ChatBubbleBottomCenterText size="40" color={random_hex_color_code()} />
<Icon.ChatBubbleLeft size="40" color={random_hex_color_code()} />
<Icon.ChatBubbleLeftEllipsis size="40" color={random_hex_color_code()} />
<Icon.ChatBubbleLeftRight size="40" color={random_hex_color_code()} />
<Icon.ChatBubbleOvalLeft size="40" color={random_hex_color_code()} />
<Icon.ChatBubbleOvalLeftEllipsis size="40" color={random_hex_color_code()} />
<Icon.Check size="40" color={random_hex_color_code()} />
<Icon.CheckBadge size="40" color={random_hex_color_code()} />
<Icon.CheckCircle size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleDown size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleLeft size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleRight size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleUp size="40" color={random_hex_color_code()} />
<Icon.ChevronDown size="40" color={random_hex_color_code()} />
<Icon.ChevronLeft size="40" color={random_hex_color_code()} />
<Icon.ChevronRight size="40" color={random_hex_color_code()} />
<Icon.ChevronUp size="40" color={random_hex_color_code()} />
<Icon.ChevronUpDown size="40" color={random_hex_color_code()} />
<Icon.CircleStack size="40" color={random_hex_color_code()} />
<Icon.Clipboard size="40" color={random_hex_color_code()} />
<Icon.ClipboardDocument size="40" color={random_hex_color_code()} />
<Icon.ClipboardDocumentCheck size="40" color={random_hex_color_code()} />
<Icon.ClipboardDocumentList size="40" color={random_hex_color_code()} />
<Icon.Clock size="40" color={random_hex_color_code()} />
<Icon.Cloud size="40" color={random_hex_color_code()} />
<Icon.CloudArrowDown size="40" color={random_hex_color_code()} />
<Icon.CloudArrowUp size="40" color={random_hex_color_code()} />
<Icon.CodeBracket size="40" color={random_hex_color_code()} />
<Icon.CodeBracketSquare size="40" color={random_hex_color_code()} />
<Icon.Cog size="40" color={random_hex_color_code()} />
<Icon.Cog6Tooth size="40" color={random_hex_color_code()} />
<Icon.Cog8Tooth size="40" color={random_hex_color_code()} />
<Icon.CommandLine size="40" color={random_hex_color_code()} />
<Icon.ComputerDesktop size="40" color={random_hex_color_code()} />
<Icon.CpuChip size="40" color={random_hex_color_code()} />
<Icon.CreditCard size="40" color={random_hex_color_code()} />
<Icon.Cube size="40" color={random_hex_color_code()} />
<Icon.CurrencyDollar size="40" color={random_hex_color_code()} />
<Icon.CurrencyEuro size="40" color={random_hex_color_code()} />
<Icon.CurrencyPound size="40" color={random_hex_color_code()} />
<Icon.CurrencyRupee size="40" color={random_hex_color_code()} />
<Icon.CurrencyYen size="40" color={random_hex_color_code()} />
<Icon.CursorArrowRays size="40" color={random_hex_color_code()} />
<Icon.CursorArrowRipple size="40" color={random_hex_color_code()} />
<Icon.DevicePhoneMobile size="40" color={random_hex_color_code()} />
<Icon.DeviceTablet size="40" color={random_hex_color_code()} />
<Icon.Document size="40" color={random_hex_color_code()} />
<Icon.DocumentArrowDown size="40" color={random_hex_color_code()} />
<Icon.DocumentArrowUp size="40" color={random_hex_color_code()} />
<Icon.DocumentChartBar size="40" color={random_hex_color_code()} />
<Icon.DocumentCheck size="40" color={random_hex_color_code()} />
<Icon.DocumentDuplicate size="40" color={random_hex_color_code()} />
<Icon.DocumentMagnifyingGlass size="40" color={random_hex_color_code()} />
<Icon.DocumentMinus size="40" color={random_hex_color_code()} />
<Icon.DocumentPlus size="40" color={random_hex_color_code()} />
<Icon.DocumentText size="40" color={random_hex_color_code()} />
<Icon.EllipsisHorizontal size="40" color={random_hex_color_code()} />
<Icon.EllipsisHorizontalCircle size="40" color={random_hex_color_code()} />
<Icon.EllipsisVertical size="40" color={random_hex_color_code()} />
<Icon.Envelope size="40" color={random_hex_color_code()} />
<Icon.EnvelopeOpen size="40" color={random_hex_color_code()} />
<Icon.ExclamationCircle size="40" color={random_hex_color_code()} />
<Icon.ExclamationTriangle size="40" color={random_hex_color_code()} />
<Icon.Eye size="40" color={random_hex_color_code()} />
<Icon.EyeSlash size="40" color={random_hex_color_code()} />
<Icon.FaceFrown size="40" color={random_hex_color_code()} />
<Icon.FaceSmile size="40" color={random_hex_color_code()} />
<Icon.Film size="40" color={random_hex_color_code()} />
<Icon.FingerPrint size="40" color={random_hex_color_code()} />
<Icon.Fire size="40" color={random_hex_color_code()} />
<Icon.Flag size="40" color={random_hex_color_code()} />
<Icon.Folder size="40" color={random_hex_color_code()} />
<Icon.FolderArrowDown size="40" color={random_hex_color_code()} />
<Icon.FolderMinus size="40" color={random_hex_color_code()} />
<Icon.FolderOpen size="40" color={random_hex_color_code()} />
<Icon.FolderPlus size="40" color={random_hex_color_code()} />
<Icon.Forward size="40" color={random_hex_color_code()} />
<Icon.Funnel size="40" color={random_hex_color_code()} />
<Icon.Gif size="40" color={random_hex_color_code()} />
<Icon.Gift size="40" color={random_hex_color_code()} />
<Icon.GiftTop size="40" color={random_hex_color_code()} />
<Icon.GlobeAlt size="40" color={random_hex_color_code()} />
<Icon.GlobeAmericas size="40" color={random_hex_color_code()} />
<Icon.GlobeAsiaAustralia size="40" color={random_hex_color_code()} />
<Icon.GlobeEuropeAfrica size="40" color={random_hex_color_code()} />
<Icon.HandRaised size="40" color={random_hex_color_code()} />
<Icon.HandThumbDown size="40" color={random_hex_color_code()} />
<Icon.HandThumbUp size="40" color={random_hex_color_code()} />
<Icon.Hashtag size="40" color={random_hex_color_code()} />
<Icon.Heart size="40" color={random_hex_color_code()} />
<Icon.Home size="40" color={random_hex_color_code()} />
<Icon.HomeModern size="40" color={random_hex_color_code()} />
<Icon.Identification size="40" color={random_hex_color_code()} />
<Icon.Inbox size="40" color={random_hex_color_code()} />
<Icon.InboxArrowDown size="40" color={random_hex_color_code()} />
<Icon.InboxStack size="40" color={random_hex_color_code()} />
<Icon.InformationCircle size="40" color={random_hex_color_code()} />
<Icon.Key size="40" color={random_hex_color_code()} />
<Icon.Language size="40" color={random_hex_color_code()} />
<Icon.Lifebuoy size="40" color={random_hex_color_code()} />
<Icon.LightBulb size="40" color={random_hex_color_code()} />
<Icon.Link size="40" color={random_hex_color_code()} />
<Icon.ListBullet size="40" color={random_hex_color_code()} />
<Icon.LockClosed size="40" color={random_hex_color_code()} />
<Icon.LockOpen size="40" color={random_hex_color_code()} />
<Icon.MagnifyingGlass size="40" color={random_hex_color_code()} />
<Icon.MagnifyingGlassCircle size="40" color={random_hex_color_code()} />
<Icon.MagnifyingGlassMinus size="40" color={random_hex_color_code()} />
<Icon.MagnifyingGlassPlus size="40" color={random_hex_color_code()} />
<Icon.Map size="40" color={random_hex_color_code()} />
<Icon.MapPin size="40" color={random_hex_color_code()} />
<Icon.Megaphone size="40" color={random_hex_color_code()} />
<Icon.Microphone size="40" color={random_hex_color_code()} />
<Icon.Minus size="40" color={random_hex_color_code()} />
<Icon.MinusCircle size="40" color={random_hex_color_code()} />
<Icon.Moon size="40" color={random_hex_color_code()} />
<Icon.MusicalNote size="40" color={random_hex_color_code()} />
<Icon.Newspaper size="40" color={random_hex_color_code()} />
<Icon.NoSymbol size="40" color={random_hex_color_code()} />
<Icon.PaperAirplane size="40" color={random_hex_color_code()} />
<Icon.PaperClip size="40" color={random_hex_color_code()} />
<Icon.Pause size="40" color={random_hex_color_code()} />
<Icon.Pencil size="40" color={random_hex_color_code()} />
<Icon.PencilSquare size="40" color={random_hex_color_code()} />
<Icon.Phone size="40" color={random_hex_color_code()} />
<Icon.PhoneArrowDownLeft size="40" color={random_hex_color_code()} />
<Icon.PhoneArrowUpRight size="40" color={random_hex_color_code()} />
<Icon.PhoneXMark size="40" color={random_hex_color_code()} />
<Icon.Photo size="40" color={random_hex_color_code()} />
<Icon.Play size="40" color={random_hex_color_code()} />
<Icon.PlayPause size="40" color={random_hex_color_code()} />
<Icon.Plus size="40" color={random_hex_color_code()} />
<Icon.PlusCircle size="40" color={random_hex_color_code()} />
<Icon.PresentationChartBar size="40" color={random_hex_color_code()} />
<Icon.PresentationChartLine size="40" color={random_hex_color_code()} />
<Icon.Printer size="40" color={random_hex_color_code()} />
<Icon.PuzzlePiece size="40" color={random_hex_color_code()} />
<Icon.QrCode size="40" color={random_hex_color_code()} />
<Icon.QuestionMarkCircle size="40" color={random_hex_color_code()} />
<Icon.QueueList size="40" color={random_hex_color_code()} />
<Icon.Radio size="40" color={random_hex_color_code()} />
<Icon.ReceiptPercent size="40" color={random_hex_color_code()} />
<Icon.ReceiptRefund size="40" color={random_hex_color_code()} />
<Icon.RectangleGroup size="40" color={random_hex_color_code()} />
<Icon.RectangleStack size="40" color={random_hex_color_code()} />
<Icon.Rss size="40" color={random_hex_color_code()} />
<Icon.Scale size="40" color={random_hex_color_code()} />
<Icon.Scissors size="40" color={random_hex_color_code()} />
<Icon.Server size="40" color={random_hex_color_code()} />
<Icon.ServerStack size="40" color={random_hex_color_code()} />
<Icon.Share size="40" color={random_hex_color_code()} />
<Icon.ShieldCheck size="40" color={random_hex_color_code()} />
<Icon.ShieldExclamation size="40" color={random_hex_color_code()} />
<Icon.ShoppingBag size="40" color={random_hex_color_code()} />
<Icon.ShoppingCart size="40" color={random_hex_color_code()} />
<Icon.Signal size="40" color={random_hex_color_code()} />
<Icon.SignalSlash size="40" color={random_hex_color_code()} />
<Icon.Sparkles size="40" color={random_hex_color_code()} />
<Icon.SpeakerWave size="40" color={random_hex_color_code()} />
<Icon.SpeakerXMark size="40" color={random_hex_color_code()} />
<Icon.Square2Stack size="40" color={random_hex_color_code()} />
<Icon.Squares2x2 size="40" color={random_hex_color_code()} />
<Icon.SquaresPlus size="40" color={random_hex_color_code()} />
<Icon.Star size="40" color={random_hex_color_code()} />
<Icon.Stop size="40" color={random_hex_color_code()} />
<Icon.Sun size="40" color={random_hex_color_code()} />
<Icon.Swatch size="40" color={random_hex_color_code()} />
<Icon.TableCells size="40" color={random_hex_color_code()} />
<Icon.Tag size="40" color={random_hex_color_code()} />
<Icon.Ticket size="40" color={random_hex_color_code()} />
<Icon.Trash size="40" color={random_hex_color_code()} />
<Icon.Truck size="40" color={random_hex_color_code()} />
<Icon.User size="40" color={random_hex_color_code()} />
<Icon.UserCircle size="40" color={random_hex_color_code()} />
<Icon.UserGroup size="40" color={random_hex_color_code()} />
<Icon.UserPlus size="40" color={random_hex_color_code()} />
<Icon.Users size="40" color={random_hex_color_code()} />
<Icon.VideoCamera size="40" color={random_hex_color_code()} />
<Icon.VideoCameraSlash size="40" color={random_hex_color_code()} />
<Icon.ViewColumns size="40" color={random_hex_color_code()} />
<Icon.Wifi size="40" color={random_hex_color_code()} />
<Icon.Wrench size="40" color={random_hex_color_code()} />
<Icon.WrenchScrewdriver size="40" color={random_hex_color_code()} />
<Icon.XCircle size="40" color={random_hex_color_code()} />
<Icon.XMark size="40" color={random_hex_color_code()} />

<AcademicCap />
