<script>
	import * as Icon from '$lib';
	const random_hex_color_code = () => {
		let n = (Math.random() * 0xfffff * 1000000).toString(16);
		return '#' + n.slice(0, 6);
	};
</script>

<Icon.AcademicCap variation="solid" size="40" color={random_hex_color_code()} />
<Icon.AdjustmentsHorizontal variation="solid" size="40" color={random_hex_color_code()} />
<Icon.AdjustmentsVertical variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArchiveBox variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArchiveBoxArrowDown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArchiveBoxXMark variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowDown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowDownCircle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowDownLeft variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowDownOnSquare variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowDownOnSquareStack variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowDownRight variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowDownTray variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowLeft variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowLeftCircle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowLeftOnRectangle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowLongDown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowLongLeft variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowLongRight variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowLongUp variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowPath variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowRight variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowRightCircle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowRightOnRectangle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowTopRightOnSquare variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowTrendingDown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowTrendingUp variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowUp variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowUpCircle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowUpLeft variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowUpOnSquare variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowUpOnSquareStack variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowUpRight variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowUpTray variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowUturnDown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowUturnLeft variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowUturnRight variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowUturnUp variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowsPointingIn variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowsPointingOut variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowsRightLeft variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ArrowsUpDown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.AtSymbol variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Backspace variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Backward variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Banknotes variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Bars2 variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Bars3 variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Bars3BottomLeft variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Bars3BottomRight variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Bars3CenterLeft variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Bars4 variation="solid" size="40" color={random_hex_color_code()} />
<Icon.BarsArrowDown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.BarsArrowUp variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Beaker variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Bell variation="solid" size="40" color={random_hex_color_code()} />
<Icon.BellAlert variation="solid" size="40" color={random_hex_color_code()} />
<Icon.BellSlash variation="solid" size="40" color={random_hex_color_code()} />
<Icon.BellSnooze variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Bolt variation="solid" size="40" color={random_hex_color_code()} />
<Icon.BoltSlash variation="solid" size="40" color={random_hex_color_code()} />
<Icon.BookOpen variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Bookmark variation="solid" size="40" color={random_hex_color_code()} />
<Icon.BookmarkSlash variation="solid" size="40" color={random_hex_color_code()} />
<Icon.BookmarkSquare variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Briefcase variation="solid" size="40" color={random_hex_color_code()} />
<Icon.BuildingLibrary variation="solid" size="40" color={random_hex_color_code()} />
<Icon.BuildingOffice variation="solid" size="40" color={random_hex_color_code()} />
<Icon.BuildingOffice2 variation="solid" size="40" color={random_hex_color_code()} />
<Icon.BuildingStorefront variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Cake variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Calculator variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Calendar variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CalendarDays variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Camera variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChartBar variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChartBarSquare variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChartPie variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChatBubbleBottomCenter variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChatBubbleBottomCenterText variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChatBubbleLeft variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChatBubbleLeftEllipsis variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChatBubbleLeftRight variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChatBubbleOvalLeft variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChatBubbleOvalLeftEllipsis variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Check variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CheckBadge variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CheckCircle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleDown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleLeft variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleRight variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleUp variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChevronDown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChevronLeft variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChevronRight variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChevronUp variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ChevronUpDown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CircleStack variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Clipboard variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ClipboardDocument variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ClipboardDocumentCheck variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ClipboardDocumentList variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Clock variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Cloud variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CloudArrowDown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CloudArrowUp variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CodeBracket variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CodeBracketSquare variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Cog variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Cog6Tooth variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Cog8Tooth variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CommandLine variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ComputerDesktop variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CpuChip variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CreditCard variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Cube variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CurrencyDollar variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CurrencyEuro variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CurrencyPound variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CurrencyRupee variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CurrencyYen variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CursorArrowRays variation="solid" size="40" color={random_hex_color_code()} />
<Icon.CursorArrowRipple variation="solid" size="40" color={random_hex_color_code()} />
<Icon.DevicePhoneMobile variation="solid" size="40" color={random_hex_color_code()} />
<Icon.DeviceTablet variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Document variation="solid" size="40" color={random_hex_color_code()} />
<Icon.DocumentArrowDown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.DocumentArrowUp variation="solid" size="40" color={random_hex_color_code()} />
<Icon.DocumentChartBar variation="solid" size="40" color={random_hex_color_code()} />
<Icon.DocumentCheck variation="solid" size="40" color={random_hex_color_code()} />
<Icon.DocumentDuplicate variation="solid" size="40" color={random_hex_color_code()} />
<Icon.DocumentMagnifyingGlass variation="solid" size="40" color={random_hex_color_code()} />
<Icon.DocumentMinus variation="solid" size="40" color={random_hex_color_code()} />
<Icon.DocumentPlus variation="solid" size="40" color={random_hex_color_code()} />
<Icon.DocumentText variation="solid" size="40" color={random_hex_color_code()} />
<Icon.EllipsisHorizontal variation="solid" size="40" color={random_hex_color_code()} />
<Icon.EllipsisHorizontalCircle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.EllipsisVertical variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Envelope variation="solid" size="40" color={random_hex_color_code()} />
<Icon.EnvelopeOpen variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ExclamationCircle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ExclamationTriangle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Eye variation="solid" size="40" color={random_hex_color_code()} />
<Icon.EyeSlash variation="solid" size="40" color={random_hex_color_code()} />
<Icon.FaceFrown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.FaceSmile variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Film variation="solid" size="40" color={random_hex_color_code()} />
<Icon.FingerPrint variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Fire variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Flag variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Folder variation="solid" size="40" color={random_hex_color_code()} />
<Icon.FolderArrowDown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.FolderMinus variation="solid" size="40" color={random_hex_color_code()} />
<Icon.FolderOpen variation="solid" size="40" color={random_hex_color_code()} />
<Icon.FolderPlus variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Forward variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Funnel variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Gif variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Gift variation="solid" size="40" color={random_hex_color_code()} />
<Icon.GiftTop variation="solid" size="40" color={random_hex_color_code()} />
<Icon.GlobeAlt variation="solid" size="40" color={random_hex_color_code()} />
<Icon.GlobeAmericas variation="solid" size="40" color={random_hex_color_code()} />
<Icon.GlobeAsiaAustralia variation="solid" size="40" color={random_hex_color_code()} />
<Icon.GlobeEuropeAfrica variation="solid" size="40" color={random_hex_color_code()} />
<Icon.HandRaised variation="solid" size="40" color={random_hex_color_code()} />
<Icon.HandThumbDown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.HandThumbUp variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Hashtag variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Heart variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Home variation="solid" size="40" color={random_hex_color_code()} />
<Icon.HomeModern variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Identification variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Inbox variation="solid" size="40" color={random_hex_color_code()} />
<Icon.InboxArrowDown variation="solid" size="40" color={random_hex_color_code()} />
<Icon.InboxStack variation="solid" size="40" color={random_hex_color_code()} />
<Icon.InformationCircle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Key variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Language variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Lifebuoy variation="solid" size="40" color={random_hex_color_code()} />
<Icon.LightBulb variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Link variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ListBullet variation="solid" size="40" color={random_hex_color_code()} />
<Icon.LockClosed variation="solid" size="40" color={random_hex_color_code()} />
<Icon.LockOpen variation="solid" size="40" color={random_hex_color_code()} />
<Icon.MagnifyingGlass variation="solid" size="40" color={random_hex_color_code()} />
<Icon.MagnifyingGlassCircle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.MagnifyingGlassMinus variation="solid" size="40" color={random_hex_color_code()} />
<Icon.MagnifyingGlassPlus variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Map variation="solid" size="40" color={random_hex_color_code()} />
<Icon.MapPin variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Megaphone variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Microphone variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Minus variation="solid" size="40" color={random_hex_color_code()} />
<Icon.MinusCircle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Moon variation="solid" size="40" color={random_hex_color_code()} />
<Icon.MusicalNote variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Newspaper variation="solid" size="40" color={random_hex_color_code()} />
<Icon.NoSymbol variation="solid" size="40" color={random_hex_color_code()} />
<Icon.PaperAirplane variation="solid" size="40" color={random_hex_color_code()} />
<Icon.PaperClip variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Pause variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Pencil variation="solid" size="40" color={random_hex_color_code()} />
<Icon.PencilSquare variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Phone variation="solid" size="40" color={random_hex_color_code()} />
<Icon.PhoneArrowDownLeft variation="solid" size="40" color={random_hex_color_code()} />
<Icon.PhoneArrowUpRight variation="solid" size="40" color={random_hex_color_code()} />
<Icon.PhoneXMark variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Photo variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Play variation="solid" size="40" color={random_hex_color_code()} />
<Icon.PlayPause variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Plus variation="solid" size="40" color={random_hex_color_code()} />
<Icon.PlusCircle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.PresentationChartBar variation="solid" size="40" color={random_hex_color_code()} />
<Icon.PresentationChartLine variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Printer variation="solid" size="40" color={random_hex_color_code()} />
<Icon.PuzzlePiece variation="solid" size="40" color={random_hex_color_code()} />
<Icon.QrCode variation="solid" size="40" color={random_hex_color_code()} />
<Icon.QuestionMarkCircle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.QueueList variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Radio variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ReceiptPercent variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ReceiptRefund variation="solid" size="40" color={random_hex_color_code()} />
<Icon.RectangleGroup variation="solid" size="40" color={random_hex_color_code()} />
<Icon.RectangleStack variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Rss variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Scale variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Scissors variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Server variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ServerStack variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Share variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ShieldCheck variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ShieldExclamation variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ShoppingBag variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ShoppingCart variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Signal variation="solid" size="40" color={random_hex_color_code()} />
<Icon.SignalSlash variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Sparkles variation="solid" size="40" color={random_hex_color_code()} />
<Icon.SpeakerWave variation="solid" size="40" color={random_hex_color_code()} />
<Icon.SpeakerXMark variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Square2Stack variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Squares2x2 variation="solid" size="40" color={random_hex_color_code()} />
<Icon.SquaresPlus variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Star variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Stop variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Sun variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Swatch variation="solid" size="40" color={random_hex_color_code()} />
<Icon.TableCells variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Tag variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Ticket variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Trash variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Truck variation="solid" size="40" color={random_hex_color_code()} />
<Icon.User variation="solid" size="40" color={random_hex_color_code()} />
<Icon.UserCircle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.UserGroup variation="solid" size="40" color={random_hex_color_code()} />
<Icon.UserPlus variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Users variation="solid" size="40" color={random_hex_color_code()} />
<Icon.VideoCamera variation="solid" size="40" color={random_hex_color_code()} />
<Icon.VideoCameraSlash variation="solid" size="40" color={random_hex_color_code()} />
<Icon.ViewColumns variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Wifi variation="solid" size="40" color={random_hex_color_code()} />
<Icon.Wrench variation="solid" size="40" color={random_hex_color_code()} />
<Icon.WrenchScrewdriver variation="solid" size="40" color={random_hex_color_code()} />
<Icon.XCircle variation="solid" size="40" color={random_hex_color_code()} />
<Icon.XMark variation="solid" size="40" color={random_hex_color_code()} />
